
 LIST P=16F877A
 #include "p16f877a.inc"

; CONFIG
; __config 0x3FF9
 __CONFIG _FOSC_XT & _WDTE_OFF & _PWRTE_OFF & _BOREN_ON & _LVP_ON & _CPD_OFF & _WRT_OFF & _CP_OFF

 
DATO EQU 0X20
CONT EQU 0X21

        ORG       0X0
        GOTO      MAIN
        ORG        0X4
        GOTO INTERR
        ORG       0X5
MAIN  
      BANKSEL PORTA
      MOVLW b'11000000'
      MOVWF INTCON
      BANKSEL PIE1
      BSF PIE1,RCIE
      CLRF TRISB ; USAR RB1, RB2, RB4, RB5
      BCF TXSTA,SYNC
      BSF TXSTA,BRGH
      MOVLW .25
      MOVWF SPBRG
      MOVLW   B'00010111'
      MOVWF   OPTION_REG
      BANKSEL RCSTA
      BSF RCSTA, SPEN
      BSF RCSTA, CREN
      BCF RCSTA, RX9
      BANKSEL RCREG
      CLRF PORTB
      
      ;PWM
      
      BANKSEL TRISC
      BSF TRISC,2     ;CONFIGURO COMO ENTRADA RC2
      MOVLW .250
      MOVWF PR2
      BANKSEL CCP1CON
      BSF CCP1CON,2
      BSF CCP1CON,3
      MOVLW b'10111011'	    ;PWM 75%
      MOVWF CCPR1L
      BCF CCP1CON,4
      BSF CCP1CON,5
      BCF PIR2, TMR2IF
      BSF T2CON, 0	    ;PRESCALER TMR2=4
      BCF T2CON, 1
      BSF T2CON, TMR2ON
      BTFSS PIR1,TMR2IF
      GOTO $-1
      BANKSEL TRISC
      BCF TRISC,2
      BANKSEL PORTB
            
      
      GOTO $
		
INTERR
	MOVF RCREG,W
	MOVWF DATO
	CLRF RCREG
	BTFSC DATO,0
	GOTO AVANZAR
	BTFSC DATO,1
	GOTO RETROCEDE
	BTFSC DATO,2
	GOTO DERECHA
	BTFSC DATO,3
	GOTO IZQUIERDA
	BTFSC DATO,4
	GOTO STOP
	BTFSC DATO,5
	GOTO _100
	BTFSC DATO,6
	GOTO _50
	BTFSC DATO,7
	GOTO _25
	
	
FIN	
        
	RETFIE
      

AVANZAR
	BTFSC PORTB,RB1
	BCF PORTB,RB1
	BSF PORTB,RB2
	GOTO FIN
RETROCEDE
	BTFSC PORTB,RB2
	BCF PORTB,RB2
	BSF PORTB,RB1	
	GOTO FIN
DERECHA
	;BTFSC PORTB,RB4
	;GOTO VOLVER_A_IZQ
	GOTO GO_DER
	GOTO FIN
IZQUIERDA
	;BTFSC PORTB,RB5
	;GOTO VOLVER_A_DER
	GOTO GO_IZQ
	GOTO FIN
STOP      
	BCF PORTB,RB1
	BCF PORTB,RB2
	
	GOTO FIN


GO_DER
	BSF PORTB,RB5
	CALL RETARDO_T1
	BCF PORTB,RB5
	GOTO FIN
GO_IZQ
	BSF PORTB,RB4
	CALL RETARDO_T1
	BCF PORTB,RB4
	GOTO FIN
	
_100
	MOVLW b'10111011'	    ;PWM 75%
	MOVWF CCPR1L
	BCF CCP1CON,4
	BSF CCP1CON,5
	GOTO FIN
	
_50
	MOVLW b'01100100'	    ;PWM 50%
	MOVWF CCPR1L
	BCF CCP1CON,4
	BCF CCP1CON,5
	GOTO FIN

_25
	MOVLW b'00110010'	    ;PWM 25%
	MOVWF CCPR1L
	BCF CCP1CON,4
	BCF CCP1CON,5
	GOTO FIN
	
RETARDO_250
	MOVLW .250
	MOVWF CONT
BUCLE
	NOP
	NOP
	DECFSZ CONT,F
	GOTO BUCLE
	RETURN
RETARDO_T1
	 MOVLW  .150   ;genero un retardo de 3.3ms
	 MOVWF  TMR0
	 BCF    INTCON,T0IF
	 BTFSS  INTCON,T0IF
	 GOTO $-1
	 RETURN
	RETURN
	
END